# config/coco10k_det.yaml
path: E:/git_project/deepvision-exp1/data/coco_lite10k

# 强制指定所有路径
train: images/train
val: images/val


nc: 80
names: [  # 类别名称列表（注意：COCO官方类别ID从1开始）
    "person",        # 0 (实际COCO ID:1)
    "bicycle",       # 1
    "car",           # 2
    "motorcycle",    # 3
    "airplane",      # 4
    "bus",           # 5
    "train",         # 6
    "truck",         # 7
    "boat",          # 8
    "traffic light", # 9
    "fire hydrant",  # 10
    "stop sign",     # 11
    "parking meter", # 12
    "bench",         # 13
    "bird",          # 14
    "cat",           # 15
    "dog",           # 16
    "horse",         # 17
    "sheep",         # 18
    "cow",           # 19
    "elephant",      # 20
    "bear",          # 21
    "zebra",         # 22
    "giraffe",       # 23
    "backpack",      # 24
    "umbrella",      # 25
    "handbag",       # 26
    "tie",           # 27
    "suitcase",      # 28
    "frisbee",       # 29
    "skis",          # 30
    "snowboard",     # 31
    "sports ball",   # 32
    "kite",          # 33
    "baseball bat",  # 34
    "baseball glove", # 35
    "skateboard",    # 36
    "surfboard",     # 37
    "tennis racket", # 38
    "bottle",        # 39
    "wine glass",    # 40
    "cup",           # 41
    "fork",          # 42
    "knife",         # 43
    "spoon",         # 44
    "bowl",          # 45
    "banana",        # 46
    "apple",         # 47
    "sandwich",      # 48
    "orange",        # 49
    "broccoli",      # 50
    "carrot",        # 51
    "hot dog",       # 52
    "pizza",         # 53
    "donut",         # 54
    "cake",          # 55
    "chair",         # 56
    "couch",         # 57
    "potted plant",  # 58
    "bed",           # 59
    "dining table",  # 60
    "toilet",        # 61
    "tv",            # 62
    "laptop",        # 63
    "mouse",         # 64
    "remote",        # 65
    "keyboard",      # 66
    "cell phone",    # 67
    "microwave",     # 68
    "oven",          # 69
    "toaster",       # 70
    "sink",          # 71
    "refrigerator",  # 72
    "book",          # 73
    "clock",         # 74
    "vase",          # 75
    "scissors",      # 76
    "teddy bear",    # 77
    "hair drier",    # 78
    "toothbrush"     # 79
]

# 下载脚本/URL（可选）
# download: https://ultralytics.com/assets/coco128.zip

# 关键说明：
# 1. COCO官方类别ID从1开始，但YOLO内部会从0开始映射
# 2. 确保annotations/instances_*.json中的categories字段完整
# 3. 图片路径示例：E:/git_project/deepvision-exp1/data/coco_lite10k/images/train/000000566245.jpg